### PR TITLE
Fix bug and allow fallback to node settings

### LINKED ISSUE #3: Messa Overide unclear
hi there

i Try to use your Addon but have several errors:

Node-RED Version: 4.0.9
Addon-Version 1.1.4 (dont know how to update to 1.1.5 since node-Red-Palette Version still 1.1.4)

The Push-Block should only send my informations from another block. so the Box "Block input overrides" is unchecked

My Custom message is seen by the Push-Block but it still transmit the standard Informationens from its own. when i let the fields title and message empty, it trows an error that fields should not empty. when the block input overrides is checked, it evens trow an error when the fields are not empty

Image

Image

Image

little help would be great:)

BR

### PR DESCRIPTION
**Pull request by friebi**
Fixes #3

### CODE REVIEW

File: nodes/push/gotify-push.js [hunk 1]
```diff
@@ -22,20 +22,18 @@ module.exports = function (RED) {
           token: serverConfig.token,
         };
 
-        if (!config.override) {
+        if (config.override) {
```
Comment (friebi) [inline nodes/push/gotify-push.js:25]: Only forcefully use node settings when override is true

File: nodes/push/gotify-push.js [hunk 2]
```diff
@@ -22,20 +22,18 @@ module.exports = function (RED) {
...
-          requestData.title = msg.title || msg.payload;
-          requestData.priority = msg.priority || 5;
-          requestData.extras = msg.extras || {};
+          requestData.message = msg.message || msg.payload || config.message;
+          requestData.title = msg.title || msg.topic || config.title;
+          requestData.priority = msg.priority || Math.round(config.priority) || 5;
+          requestData.extras = msg.extras || config.extras || {};
         }
 
-        console.log(requestData);
```
Comment (friebi) [inline nodes/push/gotify-push.js:37]: Remove debug printing in productive code.

**Comment by DomiiBunn** [comment]
Looks good to me. thanks for catching it ^.^

**Comment by friebi** [comment]
Awesome. Thank you. Could you create a release and push it to npm? :smile:

**Comment by DomiiBunn** [comment]
Already ahead of you 1.1.6 is out with your fix 

https://github.com/BaniChimu/node-red-gotify/releases/tag/1.1.6
